name: 'Text Connects AirTable Requests'
description: 'Collect Pull Request Statistic to Airtable'
inputs:
  airtable-token:
    description: 'Airtable API KEY'
    required: true
  airtable-base:
    description: 'Table Base ID'
    required: true
  airtable-sheet:
    description: 'Sheet'
    required: true
  airtable-picks:
    description: 'Expression to map PR json value into table column'
    required: false
    default: '[["url"], ["title"], ["created_at"], ["merged_at"], ["labels"]]'
  airtable-traversal:
    description: 'Traversal Json List item'
    required: false
    default: '{"labels": ["name"]}'
outputs:
    time: #id of output
      description: 'Ran OK.'
runs:
  using: 'node12'
  main: 'index.js'
